apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      volumes:
        - name: sample-volume
      persistentVolumeClaim: 
          claimName: my-pvc
      containers:
      - name: flaskapp
        image: nischaybl18/flaskapp:latest
        ports:
        - containerPort: 8080
