apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flaskapp
  annotations:
    kubernetes.io/ingress.class: ingress-nginx
spec:
  rules:
  - host: flash.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/flash"
        backend:
          service:
            name: flaskapp
            port:
              number: 5000
