apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: path-ingress
spec:
  rules:
   - host: test.example.com
      http:
      paths:
   - backend:
      serviceName: flaskapp
      servicePort: 8080
				
