apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv	
spec: 
    storageClassName: local
    capacity:
      storage: 10Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: /app/local
